### ISSUE TITLE
[STEEMHUNT] Failure to Load Photos

### ISSUE THREAD

**Issue by avnigenc** [Steemhunt/web#77] opened 2018-03-17 00:20 UTC
#### Expected behavior
All the projects listed on the page should have photos. In the same way, when you click on the same window on the left side of the customized window should be uploaded photos about the project.

#### Actual behavior
Photos are not loaded properly at home and on the customized page. When you click in the same way, the photo is not loaded properly on the side window.

#### How to reproduce
- Go to steemhunt.com 

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521214559/qhw0r0ltswl1iirplbow.png)

- Look any post 

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521214604/inhppj7aekvmayjey66v.png)

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521214630/z4hbcnkdhkykxyqfw4fw.png)

* Browser:   64.0.3282.186 (Official Compilation) (64 bit) Edition 
* Operating system: Win 8.1 64-bit operating system

#### Recording Of The Bug

    

![2018-03-15-17-55-43.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521216605/t1jcmmqcy9tz4palije0.gif)

 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@avnigenc/steemhunt-failure-to-upload-photos">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sydneyitguy** [comment] 2018-03-17 11:51
@avnigenc 
Do you still have the  issue?
I have asked about this on our Discord channel, but seems no one has the same issue like this..
I cannot reproduce it with the similar environment setup as well..

Was this issue temporary? or still the same?

**Comment by sydneyitguy** [comment] 2018-03-17 11:54
Oh and if you visit Imgur:  https://imgur.com/
Do you see all the images correctly?

**Comment by avnigenc** [comment] 2018-03-17 12:49
hello, its still same.


i cant see imgur link.

2018-03-17 14:54 GMT+03:00 sydneyitguy <notifications@github.com>:

**Comment by avnigenc** [comment] 2018-03-17 12:50
maybe local problems.. i live in turkey a lot of website banned ::)

2018-03-17 15:49 GMT+03:00 Avni Genç <avnignc@gmail.com>:

**Comment by sydneyitguy** [comment] 2018-03-18 07:12
@avnigenc Oh really... I didn't know there's a country Imgur banned.
We may use our own image server in the future, but I guess there's no other way to fix this problem..
I guess you can use VPN to solve this issue out.

This is one of the best & free VPN extension on chrome here:
https://chrome.google.com/webstore/detail/betternet-unlimited-free/gjknjjomckknofjidppipffbpoekiipm?utm_source=chrome-ntp-icon

I'll close this issue for now.

**Closed by sydneyitguy** 2018-03-18 07:12 UTC
