### ISSUE TITLE
The publishing robot should only vote on approved publications.

### ISSUE THREAD

**Issue by alejandrofz** [Steemhunt/web#230] opened 2018-07-12 23:48 UTC
#### Expected behavior

Because Steemhunt has demanding standards, some publications are rejected for including their terms such as: plagiarism, duplicate products, etc.

Your voting robot should only analyze the comments of the publications that have been approved, thus avoiding voting on duplicate publications.

#### Actual behavior

The robot analyzes and votes publications that have been previously removed from the list by the moderators.

#### Evidence of the problem.

* https://steemit.com/steemhunt/@sanmi/chris-digital-driver-assistant-the-digital-assistant-to-help-you-when-you-are-driving-car
* https://steemit.com/steemhunt/@simonaurelio/robin-hood-legends-a-game-of-puzzles-that-will-put-your-ingenuity-to-the-test
* https://steemit.com/steemhunt/@francisco2351/gnarbox-2-0-ssd-rugged-backup-device-for-cameras

**Comment by fknmayhem** [comment] 2018-07-13 05:07
None of those three linked hunts have been upvoted by Steemhunt. The Steemhunt upvote bot leaves a comment as well when upvoting, @alejandrofz.

**Comment by alejandrofz** [comment] 2018-07-13 19:34
I understand that, but it would be fair for someone to publish a product that has already been published 15 times previously. And still receive votes in your comments of PROS and CONS? I understand your point when saying that people will not know if the hunt will be accepted or not, but I insist that those votes are being lost, I believe that at this moment SteemHunt is rounding up their daily hunts between 170 and 200 fighters per day. . Clearly, each publication can have 2 approved comments from PROS and CONS so it can still afford to reject comments from rejected publications and yet more than half of the approved publications wanted no votes in the PROS and CONS comments. I ask you to think better about this suggestion.

**Comment by alejandrofz** [comment] 2018-07-13 19:38
Speaking of the links that I left, they are proof that Steemhunt bot votes the comments of PROS and CONS even after the publication was rejected and, in any case, I made the comments knowing that the publication had already been rejected. I know it was thought that way, that's why I made a contribution in "Suggestion" in utopia and not in "Search errors".

**Comment by sydneyitguy** [comment] 2018-07-14 08:41
thanks for the opinion @alejandrofz, but it's by design, so I'll close this ticket here.
You can post more suggestions on Discord #suggestion channel

**Closed by sydneyitguy** 2018-07-14 08:41 UTC
